'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { AnotherOne as AnotherOneElement, defineCustomElement as defineAnotherOne } from "stencil-library/dist/components/another-one.js";
import { ButtonEvent as ButtonEventElement, defineCustomElement as defineButtonEvent } from "stencil-library/dist/components/button-event.js";
import { CustomHello as CustomHelloElement, defineCustomElement as defineCustomHello } from "stencil-library/dist/components/custom-hello.js";
import { HardcodedValues as HardcodedValuesElement, defineCustomElement as defineHardcodedValues } from "stencil-library/dist/components/hardcoded-values.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-library/dist/components/my-component.js";
import { RocketCard as RocketCardElement, defineCustomElement as defineRocketCard } from "stencil-library/dist/components/rocket-card.js";
import { StatusBadge as StatusBadgeElement, defineCustomElement as defineStatusBadge } from "stencil-library/dist/components/status-badge.js";
import { TemplateCard as TemplateCardElement, defineCustomElement as defineTemplateCard } from "stencil-library/dist/components/template-card.js";
import { TextSnippetExpand as TextSnippetExpandElement, defineCustomElement as defineTextSnippetExpand } from "stencil-library/dist/components/text-snippet-expand.js";
import { XIcon as XIconElement, defineCustomElement as defineXIcon } from "stencil-library/dist/components/x-icon.js";

export type AnotherOneEvents = NonNullable<unknown>;

export const AnotherOne: StencilReactComponent<AnotherOneElement, AnotherOneEvents> = /*@__PURE__*/ createComponent<AnotherOneElement, AnotherOneEvents>({
    tagName: 'another-one',
    elementClass: AnotherOneElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as AnotherOneEvents,
    defineCustomElement: defineAnotherOne
});

export type ButtonEventEvents = { onCountIncreased: EventName<CustomEvent<number>> };

export const ButtonEvent: StencilReactComponent<ButtonEventElement, ButtonEventEvents> = /*@__PURE__*/ createComponent<ButtonEventElement, ButtonEventEvents>({
    tagName: 'button-event',
    elementClass: ButtonEventElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCountIncreased: 'countIncreased' } as ButtonEventEvents,
    defineCustomElement: defineButtonEvent
});

export type CustomHelloEvents = NonNullable<unknown>;

export const CustomHello: StencilReactComponent<CustomHelloElement, CustomHelloEvents> = /*@__PURE__*/ createComponent<CustomHelloElement, CustomHelloEvents>({
    tagName: 'custom-hello',
    elementClass: CustomHelloElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CustomHelloEvents,
    defineCustomElement: defineCustomHello
});

export type HardcodedValuesEvents = NonNullable<unknown>;

export const HardcodedValues: StencilReactComponent<HardcodedValuesElement, HardcodedValuesEvents> = /*@__PURE__*/ createComponent<HardcodedValuesElement, HardcodedValuesEvents>({
    tagName: 'hardcoded-values',
    elementClass: HardcodedValuesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as HardcodedValuesEvents,
    defineCustomElement: defineHardcodedValues
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type RocketCardEvents = NonNullable<unknown>;

export const RocketCard: StencilReactComponent<RocketCardElement, RocketCardEvents> = /*@__PURE__*/ createComponent<RocketCardElement, RocketCardEvents>({
    tagName: 'rocket-card',
    elementClass: RocketCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as RocketCardEvents,
    defineCustomElement: defineRocketCard
});

export type StatusBadgeEvents = NonNullable<unknown>;

export const StatusBadge: StencilReactComponent<StatusBadgeElement, StatusBadgeEvents> = /*@__PURE__*/ createComponent<StatusBadgeElement, StatusBadgeEvents>({
    tagName: 'status-badge',
    elementClass: StatusBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as StatusBadgeEvents,
    defineCustomElement: defineStatusBadge
});

export type TemplateCardEvents = NonNullable<unknown>;

export const TemplateCard: StencilReactComponent<TemplateCardElement, TemplateCardEvents> = /*@__PURE__*/ createComponent<TemplateCardElement, TemplateCardEvents>({
    tagName: 'template-card',
    elementClass: TemplateCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as TemplateCardEvents,
    defineCustomElement: defineTemplateCard
});

export type TextSnippetExpandEvents = NonNullable<unknown>;

export const TextSnippetExpand: StencilReactComponent<TextSnippetExpandElement, TextSnippetExpandEvents> = /*@__PURE__*/ createComponent<TextSnippetExpandElement, TextSnippetExpandEvents>({
    tagName: 'text-snippet-expand',
    elementClass: TextSnippetExpandElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as TextSnippetExpandEvents,
    defineCustomElement: defineTextSnippetExpand
});

export type XIconEvents = NonNullable<unknown>;

export const XIcon: StencilReactComponent<XIconElement, XIconEvents> = /*@__PURE__*/ createComponent<XIconElement, XIconEvents>({
    tagName: 'x-icon',
    elementClass: XIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as XIconEvents,
    defineCustomElement: defineXIcon
});
