/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnotherOne {
    }
    interface ButtonEvent {
        "initialCount": number;
    }
    interface CustomHello {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface HardcodedValues {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RocketCard {
        "company": string;
        "country": string;
        "description": string;
        "diameterFeet": number;
        "diameterMeters": number;
        "first_flight": string;
        "heightFeet": number;
        "heightMeters": number;
        "image": string | undefined;
        "massKg": number;
        "massLb": number;
        "name": string;
        "payload_weights": number;
        "stages": number | string;
        "type": string;
    }
    interface StatusBadge {
        /**
          * @default false
         */
        "autoRemove": boolean;
        "message": string;
        /**
          * @default false
         */
        "persistent": boolean;
        "status": 'info'|'success'|'warning'|'danger'|'critical'|'secondary';
        "ttl": number | undefined;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments": number;
        /**
          * @default false
         */
        "addComplementaryActions": boolean;
        "age": number;
        "descriptionText": string;
        "first": string;
        "job": string;
        "last": string;
    }
    interface TextSnippetExpand {
        /**
          * @default 100
         */
        "maxLength": number;
        /**
          * @default ""
         */
        "text": string;
    }
    interface XIcon {
    }
}
export interface ButtonEventCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonEventElement;
}
declare global {
    interface HTMLAnotherOneElement extends Components.AnotherOne, HTMLStencilElement {
    }
    var HTMLAnotherOneElement: {
        prototype: HTMLAnotherOneElement;
        new (): HTMLAnotherOneElement;
    };
    interface HTMLButtonEventElementEventMap {
        "countIncreased": number;
    }
    interface HTMLButtonEventElement extends Components.ButtonEvent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLButtonEventElementEventMap>(type: K, listener: (this: HTMLButtonEventElement, ev: ButtonEventCustomEvent<HTMLButtonEventElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLButtonEventElementEventMap>(type: K, listener: (this: HTMLButtonEventElement, ev: ButtonEventCustomEvent<HTMLButtonEventElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLButtonEventElement: {
        prototype: HTMLButtonEventElement;
        new (): HTMLButtonEventElement;
    };
    interface HTMLCustomHelloElement extends Components.CustomHello, HTMLStencilElement {
    }
    var HTMLCustomHelloElement: {
        prototype: HTMLCustomHelloElement;
        new (): HTMLCustomHelloElement;
    };
    interface HTMLHardcodedValuesElement extends Components.HardcodedValues, HTMLStencilElement {
    }
    var HTMLHardcodedValuesElement: {
        prototype: HTMLHardcodedValuesElement;
        new (): HTMLHardcodedValuesElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRocketCardElement extends Components.RocketCard, HTMLStencilElement {
    }
    var HTMLRocketCardElement: {
        prototype: HTMLRocketCardElement;
        new (): HTMLRocketCardElement;
    };
    interface HTMLStatusBadgeElement extends Components.StatusBadge, HTMLStencilElement {
    }
    var HTMLStatusBadgeElement: {
        prototype: HTMLStatusBadgeElement;
        new (): HTMLStatusBadgeElement;
    };
    interface HTMLTemplateCardElement extends Components.TemplateCard, HTMLStencilElement {
    }
    var HTMLTemplateCardElement: {
        prototype: HTMLTemplateCardElement;
        new (): HTMLTemplateCardElement;
    };
    interface HTMLTextSnippetExpandElement extends Components.TextSnippetExpand, HTMLStencilElement {
    }
    var HTMLTextSnippetExpandElement: {
        prototype: HTMLTextSnippetExpandElement;
        new (): HTMLTextSnippetExpandElement;
    };
    interface HTMLXIconElement extends Components.XIcon, HTMLStencilElement {
    }
    var HTMLXIconElement: {
        prototype: HTMLXIconElement;
        new (): HTMLXIconElement;
    };
    interface HTMLElementTagNameMap {
        "another-one": HTMLAnotherOneElement;
        "button-event": HTMLButtonEventElement;
        "custom-hello": HTMLCustomHelloElement;
        "hardcoded-values": HTMLHardcodedValuesElement;
        "my-component": HTMLMyComponentElement;
        "rocket-card": HTMLRocketCardElement;
        "status-badge": HTMLStatusBadgeElement;
        "template-card": HTMLTemplateCardElement;
        "text-snippet-expand": HTMLTextSnippetExpandElement;
        "x-icon": HTMLXIconElement;
    }
}
declare namespace LocalJSX {
    interface AnotherOne {
    }
    interface ButtonEvent {
        "initialCount"?: number;
        "onCountIncreased"?: (event: ButtonEventCustomEvent<number>) => void;
    }
    interface CustomHello {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface HardcodedValues {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RocketCard {
        "company"?: string;
        "country"?: string;
        "description"?: string;
        "diameterFeet"?: number;
        "diameterMeters"?: number;
        "first_flight"?: string;
        "heightFeet"?: number;
        "heightMeters"?: number;
        "image"?: string | undefined;
        "massKg"?: number;
        "massLb"?: number;
        "name"?: string;
        "payload_weights"?: number;
        "stages"?: number | string;
        "type"?: string;
    }
    interface StatusBadge {
        /**
          * @default false
         */
        "autoRemove"?: boolean;
        "message"?: string;
        /**
          * @default false
         */
        "persistent"?: boolean;
        "status"?: 'info'|'success'|'warning'|'danger'|'critical'|'secondary';
        "ttl"?: number | undefined;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments"?: number;
        /**
          * @default false
         */
        "addComplementaryActions"?: boolean;
        "age"?: number;
        "descriptionText"?: string;
        "first"?: string;
        "job"?: string;
        "last"?: string;
    }
    interface TextSnippetExpand {
        /**
          * @default 100
         */
        "maxLength"?: number;
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface XIcon {
    }
    interface IntrinsicElements {
        "another-one": AnotherOne;
        "button-event": ButtonEvent;
        "custom-hello": CustomHello;
        "hardcoded-values": HardcodedValues;
        "my-component": MyComponent;
        "rocket-card": RocketCard;
        "status-badge": StatusBadge;
        "template-card": TemplateCard;
        "text-snippet-expand": TextSnippetExpand;
        "x-icon": XIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "another-one": LocalJSX.AnotherOne & JSXBase.HTMLAttributes<HTMLAnotherOneElement>;
            "button-event": LocalJSX.ButtonEvent & JSXBase.HTMLAttributes<HTMLButtonEventElement>;
            "custom-hello": LocalJSX.CustomHello & JSXBase.HTMLAttributes<HTMLCustomHelloElement>;
            "hardcoded-values": LocalJSX.HardcodedValues & JSXBase.HTMLAttributes<HTMLHardcodedValuesElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "rocket-card": LocalJSX.RocketCard & JSXBase.HTMLAttributes<HTMLRocketCardElement>;
            "status-badge": LocalJSX.StatusBadge & JSXBase.HTMLAttributes<HTMLStatusBadgeElement>;
            "template-card": LocalJSX.TemplateCard & JSXBase.HTMLAttributes<HTMLTemplateCardElement>;
            "text-snippet-expand": LocalJSX.TextSnippetExpand & JSXBase.HTMLAttributes<HTMLTextSnippetExpandElement>;
            "x-icon": LocalJSX.XIcon & JSXBase.HTMLAttributes<HTMLXIconElement>;
        }
    }
}
